src/cbf/cashier/urls.py
from django.conf.urls import url
from rest_framework.routers import SimpleRouter

from . import views
# from .views import ProductViewSet
#
# router = SimpleRouter(trailing_slash=False)
#
# router.register(r'partners/(?P<partner_pk>\d+/)/product', ProductViewSet, base_name='partner-products')


urlpatterns = [
    url('(?P<slug>[0-9a-f-]+)/(?P<purchase_id>\d+)', views.DeleteSaleView.as_view(), name='delete_sale'),
    url('(?P<slug>[0-9a-f-]+)', views.AddSaleView.as_view(), name='add_sale'),

]

src/cbf/partners/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout_then_login
from . import views


urlpatterns = [
    # url(r'^auth', views.auth, name='auth'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r"^logout$", logout_then_login, name="logout"),
    url(r'^register$', views.RegisterView.as_view(), name='register'),
    url(r'^(?P<code>[0-9a-f-]+)/change-pass', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'forgot-pass', views.ForgotPasswordView.as_view(), name='forgot_password'),
    url(r'^setup$', views.SetupView.as_view(), name='setup'),
    url(r'^control-panel$', views.ControlPanelView.as_view(), name='control_panel'),
    url(r'^products-list$', views.ProductsListView.as_view(), name='products_list'),
    url(r'^payment-data$', views.PaymentDataView.as_view(), name='payment_data'),
    url(r'^sales$', views.SalesView.as_view(), name='sales'),
    url(r'^(?P<partner_id>\d+)/payment/(?P<invoice_number>\d+)', views.DownloadInvoiceView.as_view(),
        name='download_invoice')
]

src/cbf/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from cbf.clients.urls import urlpatterns as client_urlpatterns
from cbf.cashier.urls import urlpatterns as cashier_urlpatterns
from cbf.partners.urls import urlpatterns as partner_urlpatterns
from cbf.partners.views import BaseView
# admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clients/', include(client_urlpatterns, namespace='clients')),
    url(r'^cashier/', include(cashier_urlpatterns, namespace='cashier')),
    url(r'^partners/', include(partner_urlpatterns, namespace='partners')),
    url(r'^partners', BaseView.as_view(), name='partners'),
    # url(r'^', BaseView.as_view(), name='base_view')
]

src/cbf/partners/models.py
import uuid
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from autoslug import AutoSlugField


class Partner(models.Model):

    NEW, ACTIVATED, DEACTIVATED = 0, 1, 2

    STATUS = (
        (NEW, _('Новый')),
        (ACTIVATED, _('Активирован')),
        (DEACTIVATED, _('Деактивирован'))
    )

    # Fields
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(unique=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    payment_data = JSONField(null=True, blank=True)
    products = models.CharField(max_length=10000, null=True, blank=True, default='')
    status = models.SmallIntegerField(choices=STATUS, default=NEW)
    city = models.CharField(max_length=10000, blank=False)
    percent = models.SmallIntegerField(default=10)
    public_percent = models.SmallIntegerField(default=8)
    address = JSONField(default=dict)
    setup = models.BooleanField(default=False)
    phone = models.CharField(max_length=15, null=True, blank=True, default='')
    website = models.CharField(max_length=100, null=True, blank=True, default='')
    balance = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    # cashier_secret = AutoSlugField(unique=True)
    cashier_secret = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    # slug = AutoSlugField(populate_from='name', unique=True)

    # Relationship Fields
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='partner')

    class Meta:
        ordering = ('-created',)

    def __unicode__(self):
        return u'%s' % self.pk

    def __str__(self):
        return self.name or self.email

    def get_absolute_url(self):
        return reverse('partners_partner_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('partners_partner_update', args=(self.pk,))

    def delete(self, *args, **kwargs):
        self.user.delete()
        return super(Partner, self).delete(*args, **kwargs)

    @property
    def is_new(self):
        return self.status == self.NEW


class PartnerPayment(models.Model):
    CREATED, PAID, WITHDRAWN, CANCELED = 0, 1, 2, 3

    TRANSACTION_STATUS = (
        (CREATED, _('Создан')),
        (PAID, _('Выплачен')),
        (WITHDRAWN, _('Выведен')),
        (CANCELED, _('Отменен')),
    )

    # Fields
    invoice_number = models.CharField(max_length=100, null=True, unique=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    status = models.SmallIntegerField(choices=TRANSACTION_STATUS, default=CREATED)
    sum = models.DecimalField(max_digits=20, decimal_places=2)
    payment_date = models.DateField(null=True)

    # Relationship Fields
    partner = models.ForeignKey(Partner, related_name='payments')

    class Meta:
        ordering = ('-created',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('partners_partnerpayment_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('partners_partnerpayment_update', args=(self.pk,))

src/cbf/partners/views.py
import json
import logging
import uuid
import os
import sendgrid
from reportlab.pdfbase.ttfonts import TTFont
from sendgrid.helpers.mail import *
from reportlab.pdfbase import pdfmetrics
from io import BytesIO
from reportlab.pdfgen import canvas
from django import forms as django_forms
from django.utils import timezone
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.shortcuts import render, Http404, redirect, resolve_url
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.http import HttpResponse
from django.conf import settings
from django.core.cache import cache
from django.views.generic import View, TemplateView
from django.utils.decorators import method_decorator
from django.contrib import auth as user_auth, messages
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.contrib.auth.views import LoginView, SuccessURLAllowedHostsMixin
# from django.contrib.auth.decorators import login_required
from django.views.decorators import http, csrf
from django.contrib.auth.backends import ModelBackend

from cbf.core.utils import get_object_or_none
from cbf.users.models import PARTNER
from .utils import get_cache_key
from . import forms
from .models import Partner, PartnerPayment

logger = logging.getLogger(__name__)

UserModel = user_auth.get_user_model()
# login_form = forms.LoginForm()
# register_form = forms.RegistrationForm()
change_password_prefix = 'partners.change_password'
sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_APIKEY'))
# logger.info(os.environ.get('SENDGRIP_APIKEY'))

# next_url = None


class AuthBackend(ModelBackend):

    def authenticate(self, request, email=None, password=None, **kwargs):
        if email is None:
            email = kwargs.get('email')
        user = get_object_or_none(UserModel, email=email)
        if user and user.check_password(password) and self.user_can_authenticate(user):
            return user
        return None


class BaseView(View):
    def get(self, request, *args, **kwargs):
        return redirect('/partners/control-panel')


@method_decorator(csrf.csrf_exempt, name='dispatch')
@method_decorator(never_cache, name='dispatch')
class LoginView(View, SuccessURLAllowedHostsMixin):
    redirect_field_name = 'next'
    # next_url = None

    def get(self, request):
        next_url = self.get_success_url()
        if request.user and hasattr(request.user, 'partner'):
            if not request.user.partner.setup:
                return redirect('/partners/setup')
            if next_url:
                return redirect(next_url)
            # messages.error(request, 'Нужно выйти из текущей учетной записи прежде чем авторизоватся еще раз')
            return redirect('/partners/control-panel')
        return render(request, 'login.html', {'login_form': forms.LoginForm(),
                                              'next': next_url,
                                              'title': 'CBF Partners| Авторизация'
                                              })

    def post(self, request, *args, **kwargs):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = AuthBackend().authenticate(request, email=form.cleaned_data['email'],
                                              password=form.cleaned_data['password'])
            if user and hasattr(user, 'partner'):
                user_auth.logout(request)
                user_auth.login(request, user)
                if not user.partner.setup:
                    return redirect('/partners/setup')
                next_url = self.get_success_url()
                if next_url:
                    return redirect(next_url)
                return redirect('/partners/control-panel')
            elif user:
                form.add_error(None, 'Пожалуйста, авторизируйтесь как партнер.')
            else:
                form.add_error(None, 'Либо пароль неправильный либо почта.')
        next_url = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, None)
        )
        return render(request, 'login.html', {'login_form': form,
                                              'next': next_url,
                                              'title': 'CBF Партенры | Авторизация'
                                              })

    def get_success_url(self):
        """Ensure the user-originating redirection URL is safe."""
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, None)
        )
        if not redirect_to:
            return None
        url_is_safe = is_safe_url(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        if not url_is_safe:
            return resolve_url(settings.LOGIN_REDIRECT_URL)
        return redirect_to


@method_decorator(csrf.csrf_exempt, name='dispatch')
class RegisterView(View):

    def get(self, request):
        return render(request, 'register.html', {'register_form': forms.RegistrationForm(),
                                                 'title': 'CBF Партенры | Регистрация'
                                                  })

    def post(self, request, *args, **kwargs):
        form = forms.RegistrationForm(request.POST)
        if form.is_valid():
            user = UserModel.objects.create(
                phone=form.cleaned_data.get('phone'),
                email=form.cleaned_data.get('email'),
                role=PARTNER
            )
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            Partner.objects.create(
                phone=form.cleaned_data.get('phone'),
                email=form.cleaned_data.get('email'),
                user=user,
                setup=False
            )
            user_auth.logout(request)
            user_auth.login(request, user)
            return redirect('/partners/setup')
        return render(request, 'register.html', {'register_form': form,
                                                 'title': 'CBF Партенры | Регистрация'
                                                 })


def is_partner(user, form=None):
    if not hasattr(user, 'partner'):
        if form:
            form.add_error(None, 'Пожалуйста, авторизируйтесь как партнер.')
        return False
    return True


class ForgotPasswordView(View):
    template_name = 'forgot_password.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': forms.EmailForm(),
                                                    'title': 'CBF Партенры | Восстановление пароля'
                                                    })

    def post(self, request, *args, **kwargs):
        form = forms.EmailForm(request.POST)
        if form.is_valid():
            user = get_object_or_none(UserModel, email=form.cleaned_data.get('email'))
            if user:
                if is_partner(user, form):
                    code = str(uuid.uuid4())
                    website = settings.WEBSITE
                    cache_key = get_cache_key(code, change_password_prefix)
                    cache.set(cache_key, user.email, settings.VERIFICATION_CODE_MAX_AGE)
                    message = render_to_string('change_password_email.html', {
                        'link': website + '/partners/' + code + '/change-pass',
                        'website': website,
                        'duration': round(settings.VERIFICATION_CODE_MAX_AGE / 60)
                    })
                    email = Mail(
                        from_email=Email(settings.DEFAULT_FROM_EMAIL),
                        subject='Восстановления пароля',
                        to_email=Email(user.email),
                        content=Content('text/html', message)
                    )
                    try:
                        response = sg.client.mail.send.post(request_body=email.get())
                        logger.info('Сообщение на восстановление пароля отправлен в {} с ответом {} и статусом {}'
                                    .format(user.email, response.body, response.status_code))
                        messages.success(request, 'Ссылка для восстановления пароля отправлена в почту.')
                    except Exception as e:
                        logger.error('Ошибка при отправление сообщения на почту {}'.format(e))
                        messages.error(request, 'Не удалось отправить сообщение на почту. Пропробуйте еще раз попозже.')
            else:
                messages.error(request, 'Не найдена учетная запись с такой почтой, проверите и отправьте еще раз.')
        return render(request, self.template_name, {'form': form,
                                                    'title': 'CBF Партенры | Восстановление пароля'
                                                    })


class ChangePasswordView(View):
    template_name = 'change_password.html'

    def get(self, request, code, *args, **kwargs):
        cache_key = get_cache_key(code, change_password_prefix)
        user = get_object_or_none(UserModel, email=cache.get(cache_key))
        cache.delete(cache_key)
        if not user:
            messages.error(request, 'Cсылка не правильная или устарела.')
            return redirect('/partners/forgot-pass')
        return render(request, self.template_name, {'form': forms.ChangePasswordForm(),
                                                    'code': code,
                                                    'email': user.email,
                                                    'title': 'CBF Партенры | Восстановление пароля',
                                                    })

    def post(self, request, code, *args, **kwargs):

src/cbf/partners/templates/change_password_email.html
<h3>Здраствуйте!</h3>
Переидите на <a href="{{ link }}"> ссльку </a> чтобы восстановить ваш пароль в {{ website }}.
<p>Ссылка действует {{ duration }} минут</p>

src/cbf/partners/templates/control_panel.html
{% extends 'partners_base.html' %}
{% load static %}
{#{% block local_links %}#}
{#    <script type="text/javascript" src="{% static 'js/sorttable.js' %}"></script>#}
{#{% endblock %}#}
{% block custom_style %}
    <style>
        .block-end {
            margin-bottom: 50px;
        }
        table.sortable th:not(.sorttable_sorted):not(.sorttable_sorted_reverse):not(.sorttable_nosort):after {
            content: " \25B4\25BE"
        }
        table.sortable thead {
            background-color: lightgray;
            color: #000000;
            font-weight: bold;
            cursor: default;
        }
        td, th {
            text-align: center;
        }
    </style>
{% endblock %}
{% block maincontent %}
{#{% for message in messages %}#}
{#    <div class="alert alert-{{ message.level_tag }} alert-dismissable">#}
{#        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>#}
{#        {{ message }}#}
{#    </div>#}
{#{% endfor %}#}
{#{% if not partner.payment_data %}#}
{#<p> С вами свяжутся для активации партнера. Для начала работы необходима заполнить данные платежей</p>#}
{#<a class="btn btn-primary block-end" href="{% url 'partners:payment_data' %}">Заполнить данные договора и платежей</a>#}
{#{% endif %}#}
<p class="block-end">Ваша ссылька для добавления продажа вы можете отправить ее продавцу <br>
    <a href="{{ website }}{% url 'cashier:add_sale' slug=partner.cashier_secret %}" target="_blank">{{ website }}{% url 'cashier:add_sale' slug=partner.cashier_secret %}</a></p>
<p>Продаж в этом месяце: {{ month_sales }} Р</p>
<p>Неоплаченных счетов: {{ unpaid }} Р</p>
<div>
    <table id="payments_table" class="sortable table table-striped table-bordered table-cover">
        <thead>
        <tr>
            <th>Номер счета</th>
            <th>Дата счета</th>
            <th>Дедлайн оплаты</th>
            <th>Сумма</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for payment in partner.payments.all %}
            <tr>
                <td><a class="btn btn-block" href="{% url 'partners:download_invoice' partner_id=partner.id invoice_number=payment.invoice_number%}" target="_blank">{{ payment.invoice_number }}</a></td>
                <td><span class="date" style="display: none">{{ payment.created|date:"U" }}</span>{{ payment.created }}</td>
                <td><span class="date" style="display: none">{{ payment.payment_date|date:"U" }}</span>{{ payment.payment_date }}</td>
                <td>{{ payment.sum }}</td>
                <td>{{ payment.get_status_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{#{% endif %}#}
{% endblock %}

src/cbf/partners/templates/messages.html
{% extends 'base.html' %}
{% block body %}
{% for message in messages %}
    <div class="alert alert-{{ message.level_tag }} alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ message }}
    </div>
{% endfor %}
{% endblock %}

src/cbf/partners/templates/partners_base.html
{% extends 'base.html' %}
{% load static %}
{% block local_links %}
    <script type="text/javascript" src="{% static 'js/sorttable.js' %}"></script>
    {% block custom_style %}
    {% endblock %}
    <style>
        body {
            min-height: 75rem;
            padding-top: 4.5rem;
{#            align-items: center;#}
        }

    </style>
{% endblock %}
{% block body %}
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href='{% url 'partners:control_panel' %}'>
            <img src="{% static 'images/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            CBF
        </a>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            {% block nav %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'partners:control_panel' %}">
                        Панель управления
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'partners:sales' %}">
                        Список продаж
                    </a>
                </li>
            </ul>
            {% endblock %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'partners:logout' %}">
                        Выход
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
    {% block content %}
    {% for message in messages %}
    <div class="alert alert-{{ message.level_tag }} alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ message }}
    </div>
    {% endfor %}
    {% if not partner.payment_data %}
    <div class="row col mx-auto my-auto justify-content-center align-self-center justify">
        <p> С вами свяжутся для активации партнера. Для начала работы необходимо заполнить данные платежей.</p>
        <a class="btn btn-primary block-end" href="{% url 'partners:payment_data' %}">Заполнить данные договора и платежей</a>
    </div>
    {% elif partner.is_new %}
    <div class=" row mx-auto my-auto justify-content-center align-self-center justify">
        <h2>Ожидайте активации.</h2>
    </div>
    {% else %}
    {% block maincontent %}
    {% endblock %}
    {% endif %}
    {% endblock %}
    </div>
{% endblock %}

src/cbf/partners/templates/setup.html
{% extends 'base.html' %}
{% load static %}
{% block local_links %}
    <script src="{% static 'js/typeahead.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/typeahead.css' %}">
    <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
        }
        .content {
          max-width: 100%;
          padding: 15px;
          margin: 0 auto;
        }
        .address-block {
            margin-bottom: 10px;
        }
        .address-block .form-group{
            margin-bottom: -1px;
        }
        .address-block .form-group input{
             border-radius: 0;
        }
        .address-block .last-input input {
          border-bottom-right-radius: 0.25rem;
          border-bottom-left-radius: 0.25rem;
        }
        .address-block .first-input input {
          border-top-right-radius: 0.25rem;
          border-top-left-radius: 0.25rem;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row container">
        <div class="col-sm-8">
            <h2>Добро пожаловать</h2>
            <h4>Для активации вашего аккаунта заполните необходимую информацию</h4>
            <form accept-charset="utf-8" method="post" action="{% url 'partners:setup' %}">
                {% csrf_token %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.level_tag }} alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}
                <div class="errors alert-danger">
                    {{ setup_form.non_field_errors }}
                </div>
                <div class="form-group">
                    <div class="errorlist alert-danger">
                        {{ setup_form.name.errors }}
                    </div>
                    {{ setup_form.name.label_tag }}
                    {{ setup_form.name }}
                </div>
                <div class="form-group">
                    <div class="errorlist alert-danger">
                        {{ setup_form.city.errors }}
                    </div>
                    {{ setup_form.city.label_tag }}
                    {{ setup_form.city }}
                </div>
                <div class="form-group">
                    <div class="errorlist alert-danger">
                        {{ setup_form.website.errors }}
                    </div>
                    {{ setup_form.website.label_tag }}
                    {{ setup_form.website }}
                </div>
                <div class="form-group">
                    <div class="errorlist alert-danger">
                        {{ setup_form.percent.errors }}
                    </div>
                    {{ setup_form.percent.label_tag }}
                    {{ setup_form.percent }}
                    <p>Процент делится между покупателем и пригласившим покупателя.
                        Большой процент выделит вас среди конкурентов в каталоге.
                    </p>
                </div>
                <div class="form-group">
                    <div class="errorlist alert-danger">
                        {{ setup_form.products.errors}}
                    </div>
                    {{ setup_form.products.label_tag }}
                    {{ setup_form.products }}
                </div>
                <h4>Адреса</h4>
{#                {{ setup_form.as_p }}#}
                {{ address_formset.management_form }}
                <div class="row">
                    <div class="col-sm-8">
                        <div id="formset" class="table">
                            {% with 1 as count %}
                            {% for formset in address_formset.forms %}
                                <div class="address-block">
                                    Адрес {{ forloop.counter }}
                                    <div class="errors alert-danger">
                                        {{ formset.non_field_errors }}
                                    </div>
                                    <div class="form-group first-input">
                                        <div class="errorlist alert-danger">
                                            {{ formset.address.errors }}
                                        </div>
                                        {{ formset.address }}
                                    </div>
                                    <div class="form-group">
                                        <div class="errorlist alert-danger">
                                            {{ formset.phone.errors }}
                                        </div>
                                        {{ formset.phone }}
                                    </div>
                                    <div class="form-group last-input">
                                        <div class="errorlist alert-danger">
                                            {{ formset.work_hours.errors }}
                                        </div>
                                        {{ formset.work_hours }}
                                    </div>
                                </div>
                            {% endfor %}
                            {% endwith %}
                        </div>
                        <p style="margin-bottom: 30px; margin-top: -10px"><a id="add_more" href="#">+Новый адрес</a></p>
                        <div id="empty_form" style="display:none">
                            <div class="address-block">
                                Адрес__
                                <div class="errors alert-danger">
                                        {{ address_formset.empty_form.non_field_errors }}
                                </div>
                                <div class="form-group first-input">
                                    <div class="errorlist alert-danger">
                                        {{ address_formset.empty_form.address.errors }}
                                    </div>
                                    {{ address_formset.empty_form.address }}
                                </div>
                                <div class="form-group">
                                    <div class="errorlist alert-danger">
                                        {{ address_formset.empty_form.phone.errors }}
                                    </div>
                                    {{ address_formset.empty_form.phone }}
                                </div>
                                <div class="form-group last-input">
                                    <div class="errorlist alert-danger">
                                        {{ address_formset.empty_form.work_hours.errors }}
                                    </div>
                                    {{ address_formset.empty_form.work_hours }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <input class="btn btn-primary" value="Завершить регистрацию" type="submit">
            </form>
        </div>
    </div>

    <script>
    $('#add_more').click(function(event) {
        var form_idx = $('#id_form-TOTAL_FORMS').val();
        $('#formset').append($('#empty_form').html().replace(/__prefix__/g, form_idx)
            .replace(/Адрес__/g, 'Адрес ' + (parseInt(form_idx) + 1)));
        $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
        event.preventDefault();
    });
    $("#formset").on('DOMNodeInserted', function () {
        $("input.phone").mask("+7 (999) 999-99-99");
        $("input.phone").attr("placeholder", "+7 (999) 999-99-99");
    });
    $(document).ready(function() {
        $('#id_city').keydown(function(event){
            if(event.keyCode === 13) {
                event.preventDefault();
                return false;
            }
        });
    });
    var cityList = null;
    var cityBloodhood = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    prefetch: {
        url: '/static/ref-books/russia-cities.json',
        filter: function(list) {
            cityList = list;
            console.log(list);
            return $.map(list, function(cityName) {
                return { name: cityName }; });
                }
            }
    });
    cityBloodhood.initialize();

    $('#id_city').typeahead({
        hint: true,
        highlight: true,
        minLength: 1,
        freeInput: false
    }, {
        name:'cities',
        source: cityBloodhood.ttAdapter(),
            displayKey: 'name',
        valueKey: 'name'
    }).blur(function(){
        if(!exists(Object.values(cityBloodhood.index.datums), $(this).val())) {
            $(this).val("");
        }
    });

    function exists (array, key) {
        for(var i=0; i<array.length; i++){
            if(array[i].name === key)return true;
        }
        return false;
    }

    var productsBloodhood = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    prefetch: {
        url: '/partners/products-list',
        filter: function(list) {
            return $.map(list, function(productName) {
                return { name: productName }; });
                }
            }
    });
    productsBloodhood.initialize();

    $('#id_products').tagsinput({
        typeaheadjs: {
            name: 'productsBloodhood',
            displayKey: 'name',
            valueKey: 'name',
            source: productsBloodhood.ttAdapter()
        },
        freeInput: true
    });
    </script>
{% endblock %}