src/cbf/cashier/urls.py
from django.conf.urls import url
from rest_framework.routers import SimpleRouter

from . import views
# from .views import ProductViewSet
#
# router = SimpleRouter(trailing_slash=False)
#
# router.register(r'partners/(?P<partner_pk>\d+/)/product', ProductViewSet, base_name='partner-products')


urlpatterns = [
    url('(?P<slug>[0-9a-f-]+)/(?P<purchase_id>\d+)', views.DeleteSaleView.as_view(), name='delete_sale'),
    url('(?P<slug>[0-9a-f-]+)', views.AddSaleView.as_view(), name='add_sale'),

]

src/cbf/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from cbf.clients.urls import urlpatterns as client_urlpatterns
from cbf.cashier.urls import urlpatterns as cashier_urlpatterns
from cbf.partners.urls import urlpatterns as partner_urlpatterns
from cbf.partners.views import BaseView
# admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^clients/', include(client_urlpatterns, namespace='clients')),
    url(r'^cashier/', include(cashier_urlpatterns, namespace='cashier')),
    url(r'^partners/', include(partner_urlpatterns, namespace='partners')),
    url(r'^partners', BaseView.as_view(), name='partners'),
    # url(r'^', BaseView.as_view(), name='base_view')
]

src/cbf/cashier/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from cbf.partners.models import Partner


class Seller(models.Model):
    pass


class Product(models.Model):
    name = models.CharField(_('Название'), max_length=100)
    description = models.TextField(_('Описание'), max_length=1000, null=True, blank=True)
    added = models.DateTimeField(_('Дата добавления'), auto_now_add=True)
    cost = models.FloatField(_('Стоимость'))
    sold = models.BooleanField(_('Продан'), default=False)

    partner = models.ForeignKey(Partner)

    class Meta:
        ordering = ('-added', )
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

src/cbf/cashier/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from cbf.core.utils import get_object_or_none
from cbf.clients.models import Client


UserModel = get_user_model()


class SaleForm(forms.Form):
    category = forms.CharField(label=_('Категория'),
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Категория',
                                                             'class': 'form-control',
                                                             'data-role': 'typeahead',
                                                             }))
    client_code = forms.IntegerField(label=_('Код клиента'),
                                     required=True,
                                     widget=forms.NumberInput(attrs={'placeholder': 'Код клиента',
                                                                     'class': 'form-control',
                                                                     }))

    sum = forms.FloatField(label=_('Сумма'),
                           required=True,
                           widget=forms.NumberInput(attrs={'placeholder': 'Сумма (в Рублях)',
                                                           'class': 'form-control'
                                                           }))

    def clean_client_code(self):
        code = self.cleaned_data.get('client_code')
        client = get_object_or_none(Client, code=code)
        if not client:
            raise forms.ValidationError('Клиент с таким кодом не сущестествует!', 'invalid')
        return code

src/cbf/cashier/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect, Http404
from django.template.loader import render_to_string
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import View, CreateView, DeleteView, DetailView, ListView
# from rest_framework.viewsets import ModelViewSet
#
# from cbf.partners.mixins import PartnerMixin
# from .models import Product
# from .serializers import ProductSerializer

from cbf.core.utils import get_object_or_none
from cbf.clients.models import Purchase, Client
from cbf.partners.models import Partner, PartnerPayment
from . import forms

#
# class ProductViewSet(ModelViewSet, PartnerMixin):
#
#     queryset = Product.objects.all()
#     search_fields = ('name',)
#
#     serializer_class = ProductSerializer
#
#     def get_partner_queryset(self):
#         queryset = self.partner_queryset.filter(
#             pk__in=self.request.user.partner.all()
#         )
#         return queryset
#
#     def get_queryset(self):
#         queryset = super(ProductViewSet, self).get_queryset()
#         return queryset.filter(partner=self.partner)
#
#     def perform_create(self, serializer):
#         serializer.save(partner=self.partner)


# @method_decorator(login_required, name='dispatch')


def make_data(request, html=None, new_form=None):
    messages_string = render_to_string('messages.html', request=request)
    data = dict()
    if html:
        data['html'] = html
    if new_form:
        data['new_form'] = new_form
    data['messages'] = messages_string
    return json.dumps(data)


class AddSaleView(View):

    template_name = 'cashier_page.html'
    model = Purchase
    queryset = Purchase.objects.all()
    partner = None

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': 'CBF Кассир | Добавление продажа',
                                                    'add_sale_form': forms.SaleForm(),
                                                    'cashier_secret': kwargs['slug'],
                                                    'sales': self.get_queryset(),
                                                    'product_tags': self.get_products(),
                                                    })

    def get_queryset(self):
        partner = self.get_partner()
        if not partner:
            raise Http404
        self.partner = partner
        return self.queryset.filter(partner=partner)

    def get_products(self):
        if not self.partner:
            return None
        products = set([x.strip() for x in self.partner.products.split(',') if x != ''])
        return json.dumps(list(products), ensure_ascii=False)

    def get_partner(self):
        return get_object_or_none(Partner, cashier_secret=self.kwargs['slug'])

    def post(self, request, *args, **kwargs):
        form = forms.SaleForm(request.POST)
        if form.is_valid():
            client = get_object_or_none(Client, code=form.cleaned_data.get('client_code'))
            category = form.cleaned_data.get('category')
            sum = form.cleaned_data.get('sum')
            partner = self.get_partner()
            if not partner:
                messages.error(request, 'Что-то пошло не так. Попробуйте еще раз')
                # form.add_error(None, 'Что-то пошло не так. Попробуйте еще раз')
            else:
                purchase = Purchase.objects.create(sum=sum, category=category, client=client, partner=partner)
                partner.balance -= sum
                partner.save()
                # messages.success(request, 'Продажа успешно добавлена')
                html = render_to_string('sales_row.html', context={'purchase': purchase}, request=request)
                new_form = render_to_string('add_sale_form.html',
                                            request=request,
                                            context={'add_sale_form': forms.SaleForm(),
                                                     'cashier_secret': kwargs['slug']
                                                     })
                return HttpResponse(make_data(request, html, new_form), status=200)
        html = render_to_string('add_sale_form.html', request=request, context={'add_sale_form': form,
                                                                                'cashier_secret': kwargs['slug']
                                                                                })
        return HttpResponse(make_data(request, html), status=400)


class DeleteSaleView(View):

    def delete(self, request, purchase_id, *args, **kwargs):
        purchase = get_object_or_none(Purchase, id=purchase_id)
        if purchase and purchase.partner == self.get_partner():
            purchase.delete()
            # messages.success(request, 'Продажа успешно удалена')
            return HttpResponse(make_data(request), status=200)
        else:
            messages.error(request, 'Вы не имеете права на удаление продажи.')
            return HttpResponse(make_data(request), status=400)

    def get_partner(self):
        return get_object_or_none(Partner, cashier_secret=self.kwargs['slug'])

src/cbf/cashier/templates/add_sale_form.html
<div class="form">
    <form method="post" id="new_sale_form" action="{% url 'cashier:add_sale' slug=cashier_secret %}" class="form-signin">
        {% csrf_token %}
        <h3 class="form-signin-heading">Добавление продаж</h3>
            <div class="errors">
            {{ add_sale_form.non_field_errors }}
        </div>
        <div class="field-wrap first-input">
            <div class="errors">
                {{ add_sale_form.category.errors }}
            </div>
            {{ add_sale_form.category }}
        </div>
        <div class="field-wrap">
            <div class="errors">
                {{ add_sale_form.client_code.errors }}
            </div>
            {{ add_sale_form.client_code }}
        </div>
        <div class="field-wrap last-input">
            <div class="errors">
                {{ add_sale_form.sum.errors }}
            </div>
            {{ add_sale_form.sum }}
        </div>
        <button type="submit" id="submit_sale" class="submit-sale btn btn-lg btn-block btn-primary">Добавить</button>
    </form>
</div>

src/cbf/cashier/templates/cashier_page.html
{%  extends 'base.html' %}
{% load static %}
{% block local_links %}
    <script type="text/javascript" src="{% static 'js/typeahead.js' %}"></script>
    <script src="https://rawgit.com/makeusabrew/bootbox/f3a04a57877cab071738de558581fbc91812dce9/bootbox.js"></script>
    <link rel="stylesheet" href="{% static 'css/typeahead.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <script type="text/javascript" src="{% static 'js/sorttable.js' %}"></script>
    <style>
        table.sortable {
{#            width: 70%;#}
        }
        table.sortable thead {
            background-color: lightgray;
            color: #000000;
            font-weight: bold;
            cursor: default;
        }
        table.sortable th:not(.sorttable_sorted):not(.sorttable_sorted_reverse):not(.sorttable_nosort):after {
            content: " \25B4\25BE"
        }
        body {
            padding: 30px;
            background-color: white;
        }
        .form-signin {
            margin: 10px;
        }
        td, th {
            text-align: center;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="container">
        <div id="form_div"  class="row form">
            {% include 'add_sale_form.html' %}
        </div>
        <div id="messages">
            {% include 'messages.html' %}
        </div>
        <table id="sales_table" class="sortable table table-striped table-bordered table-hover">
        <thead class="">
            <tr>
                <th>Время</th>
                <th>Сумма</th>
                <th>Категория</th>
                <th>Клиент</th>
{#                <th></th>#}
            </tr>
        </thead>
        <tbody id="sales_table_body">
            {% for sale in sales %}
                {% with sale as purchase %}
                    {% include 'sales_row.html' %}
                {% endwith %}
            {% endfor %}
        </tbody>
        </table>
    </div>
    <script>
        sorttable.sort_alpha = function(a,b) {
            return a[0].localeCompare(b[0]);
        };
        var substringMatcher = function(strs) {
            return function findMatches(q, cb) {
                var matches = [];
                var substrRegex = new RegExp(q, 'i');
                $.each(strs, function(i, str) {
                    if (substrRegex.test(str)) {
                        matches.push(str);
                    }
                });

                cb(matches);
              };
        };

        var tags  = JSON.parse("{{ product_tags }}".replace(/&quot;/g,'"'));

        function addTypeahead($selection) {
            $selection.typeahead({
                hint: true,
                highlight: true,
                minLength: 1,
                freeInput: false
            }, {
                name: 'productsBloodhood',
                source: substringMatcher(tags)
            }).blur(function(){
                if(tags.indexOf($(this).val()) === -1) {
                    $(this).val("");
                }
            });
        }
        addTypeahead($('#id_category'));

        $.delete = function(url, data, callback, type){
            if ( $.isFunction(data) ){
                type = type || callback,
                    callback = data,
                    data = {}
            }

            return $.ajax({
                url: url,
                type: 'DELETE',
                success: callback,
                data: data,
                contentType: type
            });
        };

        $(document).on('click', "#submit_sale", function (event){
            event.preventDefault();
            console.log('submit_sale button clicked');
            var url = "{% url 'cashier:add_sale' slug=cashier_secret %}";
            $.post(url, $('#new_sale_form').serialize()).done(
                function (dataRaw) {
                    var data = JSON.parse(dataRaw);
                    update_messages(data);
                    $('#sales_table_body').append(data['html']);
                    $('#form_div').html(data['new_form']).trigger('change');
                    addTypeahead($('#id_category'));
                    var myTH = document.getElementsByTagName("th")[0];
                    sorttable.innerSortFunction.apply(myTH, []);
{#                    var table = document.getElementById('sales_table');#}
{#                    sorttable.makeSortable(table);#}
{#                    sorttable.init()#}

                }
            ).fail(
                function (jqXHR, status, errorThrown) {
                    var data = JSON.parse(jqXHR.responseText);
                    update_messages(data);
                    $('#form_div').html(data['html']).trigger('change');
                    $('#submit_sale').trigger('change');
                    addTypeahead($('#id_category'));
                }
            );
        });

        $(document).on('click', '.delete', function (event) {
            event.preventDefault();
            console.log('submit_sale button clicked');
            var url = "{% url 'cashier:add_sale' slug=cashier_secret %}" + '/' + $(this).attr('id');
            var buttonId = $(this).attr('id');
            bootbox.confirm({
                size: "small",
                message: 'Вы уверены что хотите <b>удалить</b> эту продажу?',
                buttons: {
                    confirm: {
                        label: 'Да',
                        className: 'btn-danger'
                    },
                    cancel: {
                        label: 'Нет',
                        className: 'btn-success'
                    }
                },
                callback: function (result) {
                    if(result){
                        $.delete(url).done(
                            function (dataRaw) {
                                var data = JSON.parse(dataRaw);
                                update_messages(data);
                                var rowId = '#sales-row' + buttonId;
                                $(rowId).remove();
                            }
                        ).fail(
                            function (jqXHR, status, errorThrown) {
                                var data = JSON.parse(jqXHR.responseText);
                                update_messages(data);
                            }
                        );
                    }
                }
            });
        });

        function update_messages(data) {
            var messages = data['messages'];
            $('#messages').html(messages).trigger('change');
        }
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                }
            }
        });
    </script>
{% endblock %}

src/cbf/cashier/templates/messages.html
{% for message in messages %}
    <div class="alert alert-{{ message.level_tag }} alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ message }}
    </div>
{% endfor %}

src/cbf/cashier/templates/sales_row.html
{#<div class="row">#}
<tr id="sales-row{{ purchase.id }}">
    <td><span class="date" style="display: none">{{ purchase.created|date:"U" }}</span>{{ purchase.created }}</td>
    <td>{{ purchase.sum }}</td>
    <td>{{ purchase.category }}</td>
    <td>{{ purchase.client.code }}</td>
    {% if purchase.is_deletable %}
    <td><button class="btn btn-danger delete" id="{{ purchase.id }}">Удалить</button></td>
    {% endif %}
</tr>
{#</div>#}